export const CATEGORIES = [
  "Electronics",
  "Phones",
  "Laptops",
  "Computers",
  "Cars",
  "Car Parts",
  "Motorcycles",
  "Furniture",
  "Clothing",
  "Hair Accessories",
  "Fashion Accessories",
  "Books",
  "Sports",
  "Sports Equipment",
  "Real Estate",
  "Services",
  "Food & Beverages",
  "Home & Garden",
  "Toys & Games",
  "Beauty & Personal Care",
  "Health & Wellness",
  "Pet Supplies",
  "Jewelry",
  "Collectibles",
  "Other",
]
